### ISSUE TITLE
Size in CArray is int32_t?

### ISSUE THREAD

**Issue by Timmmm** [snipsco/snips-utils-rs#37]
Just discovered this - looks like exactly what I need. I was just a bit confused by this note in the docs:

```
typedef struct {
const T *values; // Pointer to the value of the list
int32_t size; // Number of T values in the list
} CArrayT;
```

Shouldn't the type of `size` be `size_t`? Or at least `uint32_t`?

Btw the link to the docs in the readme doesn't go to the latest version.

**Comment by fredszaq** [comment]
Hi @Timmmm, could you link were you've seen this ? 

The `size` in `CArray<T>` is declared as an `usize` [here](https://github.com/sonos/ffi-convert-rs/blob/main/ffi-convert/src/types.rs#L115) 


We still have a `libc::c_int` in the `CStringArray` as used to be used in conjunction with java's JNA that doesn't properly work with `size_t`. We should probably change it as we don't directly support that use case anymore

BTW I removed the hardlink to version 0.3.0 of the doc in the readme

**Comment by Timmmm** [comment]
Yeah it is [here](https://github.com/sonos/ffi-convert-rs/blob/main/ffi-convert/src/lib.rs#L134). I kind of assumed the docs were accurate because I noticed the special support for converting `usize` to `i32` [here](https://github.com/sonos/ffi-convert-rs/blob/main/ffi-convert/src/conversions.rs#L321) and on line 346 - I guess you might want to remove those if they aren't necessary any more!
