### ISSUE TITLE
How to convert from c struct efficiently

### ISSUE THREAD

**Issue by TheButlah** [snipsco/snips-utils-rs#41]
This crate looks like a good candidate for doing C# <--> Rust ffi through a C API. I will be passing C structs to C# from rust, and then sending those C structs back to rust.

My concern is that I see no way to convert the c struct back to the rust struct efficiently, as `AsRust` doesn't take ownership of the C struct. I'm assuming this was done intentionally, but I'm struggling to see why. Is there any way that I can avoid for example deep copying the `CArray`? I don't think we can even dereference it right now on the rust side without cloning the data into a `Vec`

**Comment by fredszaq** [comment]
Hi @TheButlah !

The fact that `AsRust` is copying the data from the C struct and not taking ownership of it is indeed intentionnal. The goal is not make no assumption on the C data appart from the fact that is is accessible at the moment `as_rust()` is called. In fact we can't know how the memory was allocated, if we let rust take ownership of this memory this could lead to some leaks or funky things as rust will try de-allocate the memory when you drop the value. 

If you don't want to copy the memory, you can use the `RawBorrow` trait (which is just adding an error layer on top of  [`*const T::as_ref()`](https://doc.rust-lang.org/std/primitive.pointer.html#method.as_ref)) this is however not as safe as the `AsRust` way as you basically creating a lifetime out of thin air for the data.

In the use cases we've had using this lib right now, it the Arrays we we're manipulating are not that big and we've taking the safe approach of copying the data, hence `CArray`'s API is not as rich as it could be. I'm guessing we would probably add a few standard trait impls on it ([`Index`](https://doc.rust-lang.org/std/ops/trait.Index.html) could be a good start to give access to the underlying data, maybe `Iter` as well)

If you want to add those in a PR fell free
