### ISSUE TITLE
Add conversion for fixed size arrays

### ISSUE THREAD

**Issue by curiousmindflow** [snipsco/snips-utils-rs#43]
Hello,

Could it be possible to add conversion for fixed size arrays ?
Like:
pub struct Dummy {
   a: [u8;4],
   b: [i32;12],
   ...
}

I've created a rust struct generator (using IDL representation format) that create a "pure" rust struct and the repr(C) equivalent.
This coupled with cbindgen and ffi-convert (that are key piece off the whole system, thank you !) allow me to generate a complete "chain" of data exchange C<-->Rust.

Sadly, ffi-convert lacks a feature for me, the fixed array conversion. I want to let the user of my lib create a IDL representing a specific C ABI message (for example a messaging to talk to an external device through serial/udp/tcp...) and let them use (from C) a driver (i created in Rust, on top of udp socket/serial/tcp socket...) that take and return the repr(C) struct corresponding the the IDL struct.

Since the serialization/deserialization can't be done with serde/bincode (because bincode insert the vec length in addition of the inner data) i have to use Bytemuck. But bytemuck only works with Copy types ---> fixed size arrays.

**Comment by fredszaq** [comment]
Hi @curiousmindflow thanks for your interest for this project ! 


I've created a PR #44 that add impls for CReprOf, CDrop and AsRust on array types, I'm guessing this should do what you're looking for ! 


I don't have much time to test this so if you could try it on you side and tell me if this is what you expect that would be great ! 


Have a nice day

**Comment by fredszaq** [comment]
Thinking about it, we probably need to add better types bounds to this... ie to implement CReprOf on [T; N] we probably need to have T implement CReprOf...

**Comment by fredszaq** [comment]
Updated the PR with better types bounds. The impl is a bit ugly to be honest (it uses a temporary Vec to hold the data during the conversion and prevent weird stuff in case of an error of conversion of one of the value in the array)

**Comment by curiousmindflow** [comment]
Oh, it was fast !

I will have tried it tomorrow, as soon as i have a result i will inform you, thank you :) !

**Comment by curiousmindflow** [comment]
Hi !

I tried to convert an array in unit test and also through a FFI API like so:
```Rust
#[no_mangle]
pub extern "C" fn tools_exchange_type(array: *const c_uchar) -> *const c_uchar {
    let array: [c_uchar; 4] = unsafe { slice::from_raw_parts(array, 4).try_into().unwrap() };
    let array = array.as_rust().unwrap();

    dbg!(array);

    let array: [c_uchar; 4] = CReprOf::c_repr_of(array).unwrap();
    let array = array.as_ptr();
    array
}
```

And the C side:
```C
int main() {
  char array[4] = "123\0";

  printf("array: %s\n", array);

  array[2] = '1';

  printf("array: %s\n", array);

  char *array_bis = tools_exchange_type(array);

  printf("array: %s\n", array);

  array[0] = '3';

  printf("array: %s\n", array);

  return 0;
}
```

Output:
```shell
array: 123
array: 121
[tools/src/lib.rs:27] array = [
    49,
    50,
    49,
    0,
]
array: 121
array: 321
```

It seems to work.
Can you update the derive feature to allow me to test the conversion of the array when it's in a struct please ?

**Comment by fredszaq** [comment]
As the there is an impl of `CReprOf`, `CDrop` and `AsRust` for arrays with this PR, the derives should work without any modification

**Comment by curiousmindflow** [comment]
That's what thought also, but i have an issue for those three trait in a derive attribute.
The compiler is say:
```
proc-macro derive panicked
message: Field type used in this struct is not supported by the proc macro
```

**Comment by fredszaq** [comment]
Arf indeed... should be fixed, I added a few test cases, it seems to be working, can you test with your use cases ?

**Comment by curiousmindflow** [comment]
Okay, it seems to work properly !
I was able to convert a struct with one fixed array field from C <-> Rust <-> Rust repr(C) !

Thank you :)

**Comment by curiousmindflow** [comment]
I was quick on closing the topic.
Could it be possible to upgrade the package on crates.io please ?

**Comment by fredszaq** [comment]
I'll release a 0.6.0

**Comment by fredszaq** [comment]
[0.6.0](https://crates.io/crates/ffi-convert/0.6.0) live on crates.io
