### ISSUE TITLE
Make CArray 'Clone'

### ISSUE THREAD

**Issue by curiousmindflow** [snipsco/snips-utils-rs#47]
Hello,

I need CArray<T> to be clone for my 'Message's structures to be Clone as well.

I'm using a dependency that return a reference to a 'Message' when i do a read. The 'Message's struct are behind a generic type M that have a bound Clone on it.
I can use 'to_owned()' on &M to have a M, thanks to the Clone bound.

Is it possible for you to modify CArray<T> to be Clone please ?

The other possibility for me is to require '&self' instead of 'self' in the 'c_repr_of(...)' function.
But the 'Clone' way is less restricting.

**Comment by fredszaq** [comment]
Hi @curiousmindflow !

This a slippery slope. As I told you on your PR #46, we cannot use the custom derive for that as we have a raw pointer that would need to be deep copied for the clone semantics to be respected. Such an impl of `Clone` can be written on `CArray<T>` for `T:Clone` (that would deref the raw pointer and clone the value behind). This is however at this point that things get problematic really quick: the `T`s that are gonna end up inside `CArray` are by nature `repr(C)` structs with a high probability of having raw pointers inside them (and we've seen above why the default `Clone` impl will cause some problems) 

A better way than using `to_owned()` may be to use `CArray::<YourCType>::c_repr_of(carray.as_rust())`. (or do it directly on the individual elements) This should already be possible with the current impl. 

As a side note if you do this sort of thing, beware to properly deallocate the structs from the language that allocated them in the first place (ie a `CArray` could be allocated in C and then dupplicated in rust, the first one should be deallocated by C and the second one dropped in rust)

**Comment by curiousmindflow** [comment]
Hello :)

The first part is now clear, thanks.

My problem here is i need to Clone struct that contains CArray, not the CArray directly. The struct that contains the CArray is behind a generic type T.

If the only way is to copy directly the CArray, i will need to do more code generation to generate a custom "clone" function that is different for each concrete message. It could be a pain.

**Comment by curiousmindflow** [comment]
What about the '&self' instead of the 'self' in 'c_repr_of' ?

**Comment by fredszaq** [comment]
Not really a possibility : `CString` takes ownership of a `String` to be created (thus preventing a reallocation in most cases) The goal of this trait is to have the same sort of behavior, if we pass `&self` instead of `self` it would force us to reallocate things in a few cases.

If in your specific cases you know the `CArray` will only contain "safe to clone" types, I would advise not using the one from ffi-convert but roll you own (just copy the one from the lib, the impl is rather trivial and add the clone impl that does the deep copy)
