### ISSUE TITLE
How to work `CStringArray` C type?

### ISSUE THREAD

**Issue by Masber** [snipsco/snips-utils-rs#55]
Dear ffi convert team,

I am learning go, rust and the interactions between these 2 languages by consuming rust methods by golang/cgo.

This is my rust code

```rust
use ffi_convert::RawBorrow;
use ffi_convert::{AsRust, CArray, CDrop, CReprOf, CStringArray, RawPointerConverter};
use futures::executor::block_on;
use mesa::hsm::group::r#struct::{HsmGroup, Member};
use std::ffi::{c_char, c_float, c_int, c_schar, c_uchar, c_uint, CStr};

#[repr(C)]
#[derive(CReprOf, AsRust, CDrop, RawPointerConverter, Debug)]
#[target_type(Member)]
pub struct CMember {
    #[nullable]
    ids: *const CStringArray,
}

#[repr(C)]
#[derive(CReprOf, AsRust, CDrop, RawPointerConverter, Debug)]
#[target_type(HsmGroup)]
pub struct CHsmGroup {
    label: *const libc::c_char,
    #[nullable]
    description: *const libc::c_char,
    #[nullable]
    members: *const CMember,
    #[nullable]
    exclusive_group: *const libc::c_char,
    #[nullable]
    tags: *const CStringArray,
}

#[no_mangle]
pub extern "C" fn get_hsm_group(
    data: CHsmGroup,
) {
 // do something
}
```

This is my build.rd for dbindgen

```rust
extern crate cbindgen;

use std::env;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file("bindings.h");
}
```

And this is the headers file generated

```
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct CMember {
  const CStringArray *ids;
} CMember;

typedef struct CHsmGroup {
  const char *label;
  const char *description;
  const struct CMember *members;
  const char *exclusive_group;
  const CStringArray *tags;
} CHsmGroup;

void get_hsm_group(struct CHsmGroup data);
```

My understanding is that `CStringArray` is not part of the C standard library. 

My question is:

How should I use `CStringArray`? do I need to import a library in C to use it?

Thank you very much

**Comment by fredszaq** [comment]
If you want cbindgen to parse external dependencies you need to tell it

example cbindgen conf :
```toml
[parse]
parse_deps = false
include = ["ffi-convert"]
```

To be honest, I would advise against using the `CArray` and `CStringArray` types as you need to do quite a bit conf in cbingen (you probably want to rename them as well as the C prefixed name doesn't make much sense for C headers) 

I usually prefer copying those types (from https://github.com/sonos/ffi-convert-rs/blob/main/ffi-convert/src/types.rs) into my project and rename them when I need something like that


Closing as mostly cbingen conf problem
